language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
before_install:
  - pip install codecov
install:
  - pip install -U pip setuptools
  - python setup.py install
script: make coverage
after_success:
  - codecov