language: python
sudo: false
python:
  - 2.7
  - 3.4
before_install:
  - pip install codecov
install:
  - pip install -U pip setuptools
  - python setup.py install
script: make test
after_success:
  - codecov